name: Serverless Deploy and Remove

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Serverless stage (e.g., dev)'
        required: true
        default: 'dev'
      region:
        description: 'AWS region (e.g., ap-southeast-2)'
        required: true
        default: 'ap-southeast-2'
      action:
        description: 'Action to perform (deploy or remove)'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - remove

jobs:
  deploy:
    name: Deploy Serverless Application
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Serverless Framework
        run: npm install -g serverless@3.39.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionsRole
          aws-region: ${{ github.event.inputs.region }}

      - name: Deploy with Serverless Framework
        run: serverless deploy --stage ${{ github.event.inputs.stage }} --region ${{ github.event.inputs.region }}

  remove:
    name: Remove Serverless Application
    if: github.event.inputs.action == 'remove'
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Serverless Framework
        run: npm install -g serverless@3.39.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/GitHubActionsRole
          aws-region: ${{ github.event.inputs.region }}
          env: AWS_ACCOUNT

      - name: Remove with Serverless Framework
        run: serverless remove --stage ${{ github.event.inputs.stage }} --region ${{ github.event.inputs.region }}
